---
title: "Workshop Notes"
author: "Barbara Rose Hoover"
date: "3/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Package created by JC for GitHub Collaboration
```{r}
# library(startR)
# setup(p1="BR", p2="LC")

#  library(here) : Identifies a .rproj and makes it the root directory. Never have to use setwd() every again! 
```

```{r}
new_iris()
create_dirs()
im_lazy()
look at the "Rstarter" package 
```

Staging, Committing, and Pushing through the terminal. 

```{r}
169-231-141-240:EcoDataSci beehoover$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   Untitled.R

no changes added to commit (use "git add" and/or "git commit -a")
169-231-141-240:EcoDataSci beehoover$ git add -A
169-231-141-240:EcoDataSci beehoover$ git status
On branch master
Your branch is up to date with 'origin/master'.

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   Untitled.R

169-231-141-240:EcoDataSci beehoover$ git commit -m "Added a space close #2"
```

